# Generated by Django 6.0.7 on 2026-07-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='domsname',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
            ],
        ),
    ]
