# Generated by Django 6.0.7 on 2026-07-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domsnames', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domsname',
            name='startdate',
            field=models.DateField(blank=True, default='NULL', null=True),
        ),
    ]
