# Generated by Django 6.0.7 on 2026-07-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domsnames', '0002_alter_domsname_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='domsname',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='domsname',
            name='notification_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='domsname',
            name='notification_15',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='domsname',
            name='notification_30',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='domsname',
            name='notification_7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='domsname',
            name='notification_expired',
            field=models.BooleanField(default=False),
        ),
    ]
