# Generated by Django 6.0.7 on 2026-07-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domsnames', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domsname',
            name='email',
            field=models.EmailField(blank=True, default='amine@digest-media.agency', max_length=254),
        ),
    ]
