# Generated by Django 6.0.7 on 2026-07-17 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domsnames', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='servername',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('domid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domsnames.domsname')),
            ],
        ),
    ]
