# Generated by Django 6.0.7 on 2026-07-22 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servernames', '0002_alter_servername_startdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servername',
            old_name='domid',
            new_name='serverid',
        ),
    ]
