# Generated by Django 6.0.7 on 2026-07-22 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servernames', '0003_rename_domid_servername_serverid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servername',
            name='serverid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servernames.servername'),
        ),
    ]
