# Generated by Django 6.0.7 on 2026-07-22 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servernames', '0004_alter_servername_serverid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servername',
            name='serverid',
        ),
    ]
