# Generated by Django 6.0.7 on 2026-07-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servernames', '0005_remove_servername_serverid'),
    ]

    operations = [
        migrations.AddField(
            model_name='servername',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='servername',
            name='notification_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servername',
            name='notification_15',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servername',
            name='notification_30',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servername',
            name='notification_7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servername',
            name='notification_expired',
            field=models.BooleanField(default=False),
        ),
    ]
