# Generated by Django 6.0.7 on 2026-07-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servernames', '0006_servername_email_servername_notification_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servername',
            name='email',
            field=models.EmailField(blank=True, default='amine@digest-media.agency', max_length=254),
        ),
    ]
